name = "secure-redirect-landing-new"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# Environment variables for secure configuration
[vars]
GITHUB_REPO_OWNER = "docxsigned"
GITHUB_REPO_NAME = "secure-redirect-landing"
GITHUB_BRANCH = "main"
GITHUB_API_TOKEN = ""  # Set this in Cloudflare dashboard
CACHE_TTL = "300"  # 5 minutes cache
RATE_LIMIT_MAX_REQUESTS = "10"
RATE_LIMIT_WINDOW = "60"  # 1 minute window

# KV namespace for rate limiting and caching
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "ba383042bdf947ada2c551898fcbb3f8"
preview_id = "ba383042bdf947ada2c551898fcbb3f8"

# Production environment
[env.production]
name = "secure-redirect-landing-new-prod"

# Development environment
[env.development]
name = "secure-redirect-landing-new-dev" 